management:
  server:
    port: 8081
  context-path: /actuator
  
server:
  port: 8082
  
keycloak:
  enabled: true
  realm: demo
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: emr-service
  credentials:
    secret: 3501a45b-b065-4a1f-a608-5bb0b6b08e7d
  security-constraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      patterns[0]: /emr/*